language: elixir
elixir: 1.3.3
otp_release:
  - 19.0
env:
  - MIX_ENV=test
script:
  - mix test --trace
  - mix credo --strict
after_success:
  - mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
